### ISSUE TITLE
Crash when closing CustomTabs

### ISSUE THREAD

**Issue by C10udburst** [kiwibrowser/src.next#841]
**Describe the bug**
Kiwi crashes when trying to close a Custom Tab using the "X".

**To Reproduce**
1. Launch discord app for example
2. Open any web link
3. Close using the "X" symbol on the left

**Expected behavior**
Not crashing probably would be nice.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: SM-A125F
 - Android Version: 12 (OneUI) 
 - Kiwi Browser Version: 111.0.5563.104

**Additional context**
Scoop crash log:
```
FATAL EXCEPTION: Chrome_ProcessLauncherThread
Process: com.kiwibrowser.browser, PID: 13299
Lr: child didn't handle getAppInfo() - android.os.DeadObjectException - ; browser version has changed: false
	at Nr.h(chromium-ChromeModernPublic.aab-stable-556310415:324)
	at ps.onServiceConnected(chromium-ChromeModernPublic.aab-stable-556310415:39)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2235)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2268)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by d3ward** [comment]
Hello , Kiwi got updated to v114 , do you still have that issue ?

**Comment by C10udburst** [comment]
It seems to be resolved, thank you.
