### ISSUE TITLE
Split screen crashing 

### ISSUE THREAD

**Issue by mycal123** [kiwibrowser/src.next#9]
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
	at Ep1.v(chromium-ChromePublic.apk-dev-456200115:1)
	at Ep1.w(chromium-ChromePublic.apk-dev-456200115:1)
	at Ep1.o(chromium-ChromePublic.apk-dev-456200115:1)
	at androidx.recyclerview.widget.b.j(chromium-ChromePublic.apk-dev-456200115:114)
	at Ts0.c(chromium-ChromePublic.apk-dev-456200115:9)
	at androidx.recyclerview.widget.GridLayoutManager.i1(chromium-ChromePublic.apk-dev-456200115:12)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(chromium-ChromePublic.apk-dev-456200115:12)
	at androidx.recyclerview.widget.LinearLayoutManager.l0(chromium-ChromePublic.apk-dev-456200115:119)
	at androidx.recyclerview.widget.GridLayoutManager.l0(chromium-ChromePublic.apk-dev-456200115:11)
	at androidx.recyclerview.widget.RecyclerView.t(chromium-ChromePublic.apk-dev-456200115:14)
	at androidx.recyclerview.widget.RecyclerView.r(chromium-ChromePublic.apk-dev-456200115:15)
	at androidx.recyclerview.widget.RecyclerView.o(chromium-ChromePublic.apk-dev-456200115:23)
	at Pa1.run(chromium-ChromePublic.apk-dev-456200115:6)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:822)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by mycal123** [comment]
Now fixed in new update
