### ISSUE TITLE
App crashes after open "Privacy and security" in settings

### ISSUE THREAD

**Issue by netrunner-exe** [kiwibrowser/src.next#934]
**Describe the bug**
App crashes after open "Privacy and security" in settings

**To Reproduce**
Open "Privacy and security"

**Expected behavior**
Working app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco M4 Pro 4G
 - Android Version : A12
 - Kiwi Browser Version: dev build arm64 5670848088

**Additional context**
Log:
```
java.lang.NullPointerException: Attempt to write to field 'u61 androidx.preference.Preference.o' on a null object reference in method 'void org.chromium.chrome.browser.privacy.settings.PrivacySettings.p1(java.lang.String, android.os.Bundle)'
	at org.chromium.chrome.browser.privacy.settings.PrivacySettings.p1(chromium-ChromePublic.apk-dev-584505204:161)
	at E61.J0(chromium-ChromePublic.apk-dev-584505204:68)
	at androidx.fragment.app.i.e(chromium-ChromePublic.apk-dev-584505204:45)
	at androidx.fragment.app.i.k(chromium-ChromePublic.apk-dev-584505204:124)
	at androidx.fragment.app.f.z(chromium-ChromePublic.apk-dev-584505204:1346)
	at androidx.fragment.app.f.T(chromium-ChromePublic.apk-dev-584505204:82)
	at androidx.fragment.app.f.x(chromium-ChromePublic.apk-dev-584505204:73)
	at androidx.fragment.app.f.s(chromium-ChromePublic.apk-dev-584505204:63)
	at b90.onStart(chromium-ChromePublic.apk-dev-584505204:32)
	at D9.onStart(chromium-ChromePublic.apk-dev-584505204:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1563)
	at android.app.Activity.performStart(Activity.java:8570)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by kiwibrowser** [comment]
Obviously yes, fixing it.

**Comment by kiwibrowser** [comment]
07-26 20:30:42.003 22745 22745 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.chromium.components.browser_ui.settings.ChromeBaseCheckBoxPreference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
07-26 20:30:42.003 22745 22745 E AndroidRuntime: 	at org.chromium.chrome.browser.privacy.settings.PrivacySettings.onCreatePreferences(PrivacySettings.java:161)

Coming with the next build.
Thanks a lot for the report!
